pages/urls.py
from django.urls import path

from . import views

app_name='pages'

urlpatterns=[
    path('',views.index ,name='index'),
]

polls/urls.py
from django.urls import path

from . import views

app_name='polls'

urlpatterns=[
    path('',views.index ,name='index'),
    path('<int:question_id>',views.detail,name='detail'),
    path('<int:question_id>/results',views.result,name='results'),
    path('<int:question_id>/votes',views.vote,name='vote'),

]

pollster/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('pages.urls')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('Datae Published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'pages/index.html')

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
# Create your views here.
from .models import Question,Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list':latest_question_list}
    return render(request,'polls/index.html',context)

def detail(request,question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question Does Not Exist")
    return render(request,'polls/detail.html',{'question':question})

def result(request,question_id):
    question= get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})

def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice =question.choice_set.get(pk=request.POST['choice'])
        
    except (KeyError,Choice.DoesNotExist):

        return render(request,'polls/detail.html',{
            'question': question,
            'error_message':"No choice selected!",
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Pollster {% block title %}{% endblock %}</title>
  </head>
  <body>
  {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
    <div class="card-body">
        <h1>Welcome</h1>
        <a href="{% url 'polls:index' %}" class="btn btn-dark">View Available polls</a>
    </div>
</div>
{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a href="/" class="navbar-brand">Pollster</a>
    </div>
</nav>

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %} 
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mb- 3">Poll Questions</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead">{{ question.question_text }} </p>
                    <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                    <a href="{% url 'polls:results' question.id %}" class="btn btn-primary btn-sm">Results</a>

                </div>
            </div>
        {%endfor%}
    {% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}